# Bitbucket Pipelines Template to build, test your Android Application.

# This template contains 3 parallel steps to build Android application, run Android code scanning tool and run unit tests.
# For more details see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/

# Docker for Android SDK 30 with pre-installed build tools and emulator image.
# Note: This docker image is created and maintained by a non official third party. For more details see: https://hub.docker.com/r/androidsdk/android-30
image: androidsdk/android-30

pipelines:
  branches:
    master:
      - parallel:           # running a set of steps at the same time https://support.atlassian.com/bitbucket-cloud/docs/set-up-or-run-parallel-steps/
        - step:
            name: Build
            caches:
            - gradle
            script:
            - echo $KEYSTORE_FILE_BASE64 | base64 -d > android-signing-keystore.jks
            - ./gradlew assembleRelease
            artifacts:
            - app/build/outputs/**